
name: Add malicious Link
about: 'Issue Template for Submit malicious URLs'
labels: 'Submit Link'
body:
  - type: markdown
    attributes:
      value: |
        | ⚠️ **WARNING /** | 
        |:---------------------------| 
        | Please don't open the site in your browser and don't fill out the login form!
  - type: input
    attributes:
      label: Scam URL 
    validations:
      required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Type of the Site
      description: Which scam site type is it? 
      value: Discord scam site
  - type: checkboxes 
    id: checklist 
    attributes:
      - label: Not already listed
      required: true
