name: Welcomer

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '${{ runner.NAME }} This is your **first issue** in the anti-scam-link-list repository, this is your **first Thanks for submitting the issue! ❤'
        pr-message: '${{ runner.NAME }} This is your **first pull request** in the anti-scam-link-list repository, thanks for the contribution! ❤'
